project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: REN R 231
  description: "Homepage for REN R 2113 - Introduction to Data Science at Duke University, Spring 2024."
  site-url: "https://renr213.github.io/"

  repo-url: https://github.com/sta199-s24/sta199-s24.github.io/
  repo-actions: [edit, issue]

  open-graph: true
  twitter-card:
    creator: "@minebocek"
    image: "img/twitter-card.png"

  sidebar:
    background: "#314F40" # Pantone Dark Green
    logo: "img/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/renr213
        text: "GitHub organization"
      - icon: chat-dots-fill
        href: https://edstem.org/us/courses/50730/discussion/
        text: "Ed"
      - icon: camera-reels-fill
        href: https://duke.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx?folderID=b5b29027-7084-40bf-9a2f-b0cf0100bb98
        text: "Class recordings"
      - icon: check-square-fill
        text: "Canvas"
        menu:
          - text: Gradescope
            url: https://canvas.duke.edu/courses/26106/external_tools/181
          - text: Gradebook
            url: https://canvas.duke.edu/courses/26106/gradebook

    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: index.qmd
            text: Schedule
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: course-team.qmd
            text: Instructor
          - href: course-links.qmd
            text: Useful links
          - href: course-faq.qmd
            text: FAQ
      - section: "Computing"
        contents:
          - href: computing-access.qmd
            text: Access
          - href: computing-troubleshooting.qmd
            text: Troubleshooting
          - href: computing-cheatsheets.qmd
            text: Cheatsheets
      - section: "Project"
        contents:
          - href: project/description.qmd
            text: Description
          - href: project/1-working-collaboratively.qmd
            text: Milestone 1
          - href: project/2-proposal.qmd
            text: Milestone 2
          - href: project/3-peer-review.qmd
            text: Milestone 3
          - href: project/4-writeup-presentation.qmd
            text: Milestone 4            
          - href: project/tips-resources.qmd
            text: Tips + resources
      - section: "Labs"
        contents:
          - href: labs/lab-0.qmd
            text: Lab 0
          - href: labs/lab-1.qmd
            text: Lab 1
          - href: labs/lab-2.qmd
            text: Lab 2
          - href: labs/lab-3.qmd
            text: Lab 3            
          - href: labs/lab-4.qmd
            text: Lab 4
          - href: labs/lab-5.qmd
            text: Lab 5 
          - href: labs/lab-6.qmd
            text: Lab 6             
          - href: labs/lab-7.qmd
            text: Lab 7 
      - section: "Exam review"
        contents:
          - href: exam-review/exam-1-review.qmd
            text: Exam 1
          - href: exam-review/exam-2-review.qmd
            text: Exam 2
            
  page-footer:
    right: 'This page is built with [{{< fa heart >}}]{style="color: #FFBE98;"} and [Quarto](https://quarto.org/).'
    left: "&copy; Copyright 2024, Mine Çetinkaya-Rundel"
    background: "#3A5883" # Pantone Chambray Blue - Spring 2024, darkened to pass contrast checks

format:
  html:
    theme:
      light: [cosmo, style/sta199.scss]
      dark: [cosmo, style/sta199.scss, style/dark.scss]
    linkcolor: "#3A5883" # Pantone Chambray Blue - Spring 2024, darkened to pass contrast checks
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y-dark

execute:
  freeze: auto

editor: visual
