---
title: "REN R 213 - Data Science for Resource Managers"
subtitle: "Winter 2025"
format:
  html: default
  pdf: default
---
# Syllabus

## Textbooks

All books are **freely available online**.

-   [R for Data Science, 2e](https://r4ds.hadley.nz/), Wickham, Çetinkaya-Rundel, Grolemund. O'Reilly, 2nd edition, 2023. Hard copy available [on Amazon](https://www.amazon.com/dp/1492097403?&tag=hadlwick-20).

-   [Introduction to Modern Statistics](https://openintro-ims.netlify.app/), Çetinkaya-Rundel, Hardin. OpenIntro Inc., 2nd Edition, 2023. Hard copy of 1st edition available [on Amazon](https://www.amazon.com/Introduction-Modern-Statistics-Mine-%C3%87etinkaya-Rundel/dp/1943450145/), 2nd edition currently only available online. (Either edition will work for this course.)

## Course learning objectives

By the end of the semester, you will...

-   learn to explore, visualize, and analyze data in a reproducible and shareable manner using R and RStudio
-   gain experience in data wrangling and munging, exploratory data analysis, predictive modeling, and data visualization
-   work on problems and case studies inspired by and based on real-world questions and data
-   learn to effectively communicate results through written assignments

### Accessibility

If there is any portion of the course that is not accessible to you due to challenges with technology or the course format, please let me know so we can make appropriate accommodations.

The [Academic Success Centre](https://www.ualberta.ca/en/current-students/academic-success-centre/accessibility-resources/index.html) is available to ensure that students are able to engage with their courses and related assignments.

### Communication

All lecture notes, assignment instructions, an up-to-date schedule, and other course materials may be found on the course website: [renr213.github.io](https://renr213.githug.io/ "REN R 213 - Winter 2025 course website").

Announcements will be emailed through Canvas Announcements periodically. Please check your email regularly to ensure you have the latest announcements for the course.

### Where to get help

-   If you have a question during lecture or lab, feel free to ask it! There are likely other students with the same question, so by asking you will create a learning opportunity for everyone.
-   Your instructor is here to help you be successful in the course. You are encouraged to ask questions about the course content and assignments. Many questions are most effectively answered as you discuss them with others. The [course question board](https://canvas.ualberta.ca/courses/5900/discussion_topics/27573) on Canvas is a good place for discussions.
-   Your instructor is also willing to participate in Google Meet or Zoom for discussions with one or more students

Check out the [Help](/help/) tab for more resources.

### Chat/Email

Google Chat is by far the best way to contact me (gwa\@ualberta.ca). I am usually very prompt in responding to Chat messages. If you prefer to use email, please include "REN R 213" in the subject line.

## Lectures and labs

Lectures and labs are designed to be interactive, so you gain experience applying new concepts and learning from each other. My role as instructor is to introduce you to new methods, tools, and techniques, but it is up to you to take them and make use of them. A lot of what you do in this course will involve writing code, and coding is a skill that is best learned by doing. Therefore, as much as possible, you will be working on a variety of tasks and activities throughout each lecture and lab. You are expected to prepare for class by completing assigned readings, attend all lecture and lab sessions, and meaningfully contribute to in-class exercises and discussion. Additionally, some lectures will feature application exercises that will be graded based on completing what we do in class.

You are expected to bring a laptop, tablet, or Chromebook to each class so that you can participate in the in-class exercises. Please make sure your device is fully charged before you come to class, as the number of outlets in the classroom will not be sufficient to accommodate everyone.

Lectures will be recorded and posted on Panopto (link to be shared when available) however lecture attendance is mandatory. The recordings are for catching up with classes you miss due to illness, etc. You will *not* get the most out of this class if you're not present and actively participating in it -- this is true for lectures and labs.

## Activities & Assessment

You will be assessed based on five components: application exercises, labs, exams, project, and teamwork.

### Application exercises

Parts of some lectures will be dedicated to working on Application Exercises (AEs). These exercises which give you an opportunity to practice apply the concepts and code introduced in the assignment. These AEs are due by the end of the week of the corresponding lecture period (Sunday at midnight). To submit the AEs all you need to do is to push your work to your GitHub repo.

Because these AEs are for practice, they will be graded based on completion. I define completion as a good-faith effort made in attempting all parts. Successful on-time completion of at least 80% of AEs will result in full credit for AEs in the final course grade.

### Labs

There are five graded labs for the course.

In labs, you will apply what you've learned in the videos and during lectures to complete data analysis tasks. You may discuss lab assignments with other students; however, lab sshould be completed and submitted individually. Lab assignments must be typed up using Quarto, all work must be pushed to your GitHub repository for the lab, and the PDF output of the lab must be submitted on Canvas by the deadline.

Labs are generally due on Mondays at 8:00 am MST. See [course schedule](https://renr213.github.io/) for specifics.

### Exams

There will be one exam at the end of term (April 8th). Through this exam you have the opportunity to demonstrate what you’ve learned in the course thus far. The exams will focus on both conceptual understanding of the content and application through analysis and computational tasks. The content of the exam will be related to the content in videos and reading assignments, lectures, application exercises, and labs.

More detail about the exams will be given during the semester.

## Grading

The final course grade will be calculated as follows:

| Category              | Percentage     |
|-----------------------|----------------|
| Labs                  | 70% (14% each) |
| Final Exam            | 20%            |
| Application Exercises | 10%            |

|     |
|-----|
|     |

## Five tips for success

Your success on this course depends very much on you and the effort you put into it. The course has been organized so that the burden of learning is on you. I will help you be providing you with materials and answering questions and setting the pace, but for this to work you must do the following:

1.  Complete all the preparation work.

2.  Ask questions. As often as you can. Ask me, ask your friends, ask the person sitting next to you. This will help you more than anything else. If you get a question wrong on an assessment, ask me why. If you’re not sure about the lab, ask. If you hear something on the news that sounds related to what we discussed, ask. If the reading is confusing, ask.

3.  Do the readings.

4.  Do the lab. The earlier you start, the better. It’s not enough to just mechanically plow through the exercises. You should ask yourself how these exercises relate to earlier material, and imagine how they might be changed (to make questions for an exam, for example).

5.  Don’t procrastinate. The content builds upon what was taught in previous weeks, so if something is confusing to you in Week 2, Week 3 will become more confusing, Week 4 even worse, etc. Don’t let the week end with unanswered questions. But if you find yourself falling behind and not knowing where to begin asking, come to office hours and work with a member of the teaching team to help you identify a good (re)starting point.

## Course policies

### Academic honesty

**TL;DR: Don't cheat!**

Please abide by the following as you work on assignments in this course:

-   **Collaboration:** Only work that is clearly assigned as team work should be completed collaboratively.

    -   You may discuss lab assignments with other students; however, you may not directly share (or copy) code or write up with other students. Unauthorized sharing (or copying) of the code or write up will be considered a violation for all students involved.

    -   You may not discuss or otherwise work with others on the exams. Unauthorized collaboration or using unauthorized materials will be considered a violation for all students involved. More details will be given closer to the exam date.

    -   For assignments you may not directly share work (including code) with another student in this class.

-   **Online resources:** I am well aware that a huge volume of code is available on the web to solve any number of problems. Unless I explicitly tell you not to use something, the course’s policy is that you may make use of any online resources (e.g., StackOverflow) but you must explicitly cite where you obtained any code you directly use (or use as inspiration). Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism.

-   **Use of generative artificial intelligence (AI)**: You should treat generative AI, such as GitHub Copilot or ChatGPT, the same as other online resources. There are two guiding principles that govern how you can use AI in this course:^[1](https://sta101-f23.github.io/course-syllabus.html#fn1)^

    -   *Cognitive dimension:* Working with AI should not reduce your ability to think clearly. We will practice using AI to facilitate—rather than hinder—learning.

    -   *Ethical dimension***:** Students using AI should be transparent about their use and make sure it aligns with academic integrity.

        -   **✅ AI tools for code:** You may make use of the technology for coding examples on assignments; if you do so, you must explicitly cite where you obtained the code. Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism. You may use [these guidelines](https://guides.lib.monash.edu/c.php?g=219786&p=6972087) for citing AI-generated content.

        -   **❌ AI tools for narrative:** Unless instructed otherwise, you may not use generative AI to write narrative on assignments. In general, you may use generative AI as a resource as you complete assignments but not to answer the exercises for you.

        You are ultimately responsible for the work you turn in; it should reflect *your* understanding of the course content.

If you are unsure if the use of a particular resource complies with the academic honesty policy, please ask your instructor.

Regardless of course delivery format, it is the responsibility of all students to understand and follow all University of Alberta policies, including academic integrity (e.g., completing one’s own work, following proper citation of sources, adhering to guidance around group work projects, and more). Ignoring these requirements is a violation of the University of Alberta's [Code of Student Behaviour](https://www.ualberta.ca/en/governance/resources/policies-standards-and-codes-of-conduct/code-of-student-behaviour.html).

Any violations in academic integritry standards as outlined in the [Code of Student Behaviour](https://www.ualberta.ca/en/governance/resources/policies-standards-and-codes-of-conduct/code-of-student-behaviour.html) and those specific to this course will be reported to the Dean of the Faculty of Agricultural, Life & Environmental Sciences as required by the Cod

### Late work & extensions

The due dates for assignments are there to help you keep up with the course material and to ensure the instructor can provide feedback within a timely manner. We understand that things come up that could make it difficult to submit an assignment by the deadline.

-   No late submission of labs will be accepted unless prior authorization has been given by the instructor.

-   There is no late work accepted for application exercises, since these are designed to help you prepare for other assessments in the course.

-   There is no late work accepted for exams.

### Waiver for extenuating circumstances

If there are circumstances that prevent you from completing a lab by the stated due date, you may email the instructor, [Glen Armstrong](mailto:gwa@ualberta.ca), before the deadline to waive the late penalty. In your email, you only need to request the waiver; you do not need to provide explanation.

### Attendance policy

This course is offered asynchronously. No attendance is required.

## Important dates

-   **Jan 6:** Classes begin

-   **Jan 28:** Lab 1 due

-   **Feb 11**: Lab 2 due

-   **Feb 27:** Lab 3 due

-   **Mar 13:** Lab 4 due

-   **Apr 1**: Lab 5 due.

-   **Apr 9**: Classes end. Final Exam

For more important dates, see the [University of Alberta Academic Schedule](https://calendar.ualberta.ca/content.php?catoid=44&navoid=13726).
