---
title: "Frequently Asked Questions (FAQ)"
---

## XXXX How do I export my assignment PDF from RStudio to upload to Canvas?

## XXXX How can I submit my assignment to Canvas?

## Can I use a local install of R and RStudio instead of using Posit Cloud?

The short answer is, I'd prefer if you didn't, to save yourself some headache. But, the long answer is, sure! But you will need to install a specific versions of R and RStudio for everything to work as expected. You will also need to install the R packages we're using as well as have Git installed on your computer. These are not extremely challenging things to get right, but they are not trivial either, particularly on certain operating systems. I am always happy to provide help with any computational questions when you're working in the Posit Cloud. If you're working on your local setup, we can't guarantee being able to resolve your issues, though we're happy to try.

If you want to take this path, here is what you need to do:

-   Download and install R XXX: <https://cran.r-project.org/>
-   Download and install RStudio: <https://posit.co/download/rstudio-desktop/>
-   Install Quarto XXXX: <https://quarto.org/docs/get-started/>
-   Install Git: <https://happygitwithr.com/install-git.html>
-   Install any necessary packages with `install.packages("___")`

And I'd like to reiterate again that successful installation of these software is **not** a learning goal of this course. So if any of this seems tedious or intimidating in any way, just use the computing environment (*i.e.* Posit Cloud) that I have tested the course material on.
