---
title: "Course support"
---

Most of you will need help at some point and I want to make sure you can identify when that is without getting too frustrated and that you feel comfortable seeking help.

## Office hours

This course has no official office hours. If you have a question, send me a Google Chat message. I may be able to answer the question in Chat. If not, we can set up an appointment for a Google Meeting.

## Canvas Discussion

Have a question that can't wait? Prefer to write out your question in detail rather than asking in person? The course discussion forum, Canvas discussion, is the best venue for these! Another student may have asked a similar question, so please check the other posts on before asking a new question. If you know the answer to a question that is posted, I encourage you to respond.

## Google Chat

Please refrain from trying to contact me via email. I greatly prefer Google Chat to email for course related communication.

Any course content questions (those should go to Canvas Discussion), and only use Google Chat for questions about personal matters that may not be appropriate for the public course forum (*e.g.*, illness, accommodations, *etc.*).

Use Google Chat for questions not appropriate for the public forum. Please send me a Google Chat message at gwa\@ualberta.ca**.** Barring extenuating circumstances, I will respond to REN R 213 chats within two business days.

## Academic support

There are times may need help with the class that is beyond what can be provided by the teaching team. In those instances, I encourage you to visit UAlberta's [Academic Success Centre](https://www.ualberta.ca/en/current-students/academic-success-centre/index.html).

They provide

> ... professional academic support to help students maximize their academic success and achieve their academic goals. \[They\] offer appointments, advising, group workshops, online courses, and specialized programming year-round to students in all university programs, and at all levels of achievement and study.

## Course costs

-   **Textbooks:** The textbooks for this course are freely available on the web.

-   **Internet access:** This course is offered online. Internet access (preferably broadband) is required.

-   **Web browser:** A device capable of running a web browser (*e.g.* laptop or desktop computer, Chromebook, or a tablet with a keyboard) is necessary to access course materials. The screen on the device should be large enough to work comfortably on: a mobile phone screen is probably too small.

-   **Posit Cloud Subscription:** The course is set up to use RStudio in the [Posit Cloud](https://docs.posit.co/cloud/). I recommend purchasing a Cloud Student subscription at US\$/month. However, you may find that the free subscription is sufficient (compute hours are more limited). You can upgrade your subscription to the student version later, if you wish.

    If you are comfortable installing software on your own computer, you can install the needed sofware on your own computer. You will need to install [R](https://www.r-project.org/), [RStudio Desktop](https://posit.co/download/rstudio-desktop/), and git. These software are available for free for Mac OS, Linux, and Windows computers. For Windows, I recommend the version of git found [here](https://git-scm.com/downloads/win). Please note that I will be unable to provide support for your local installation of these software.

## **Assistance with Google Meet or Canvas**

For technical help with Google Meet or Canvas, access the self-service help documentation for Google Meet [here](https://support.eclass.ualberta.ca/Knowledgebase/Article/View/404/52/using-google-meet) and for Canvas [here](https://support.eclass.ualberta.ca/Knowledgebase/Article/View/565/53/using-canvas-for-students). If this documentation does not provide an adequate answer, email IST eClass Support at [eclass\@ualberta.ca](mailto:%20eclass@ualberta.ca) or phone 780-492-9372.

Note that we will be making minimal use of Canvas in this course (primarily for announcements and grade book). All assignment submission will take place on GitHub and conversation on Ed Discussion.

Google Meet will be used for live interactions between the instructor and students.
